// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProviderCredential(arg1, arg2, arg3) {
  return window['go']['main']['App']['AddProviderCredential'](arg1, arg2, arg3);
}

export function CancelPlayground() {
  return window['go']['main']['App']['CancelPlayground']();
}

export function DeleteLocalAPIKey(arg1) {
  return window['go']['main']['App']['DeleteLocalAPIKey'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function DeleteProviderCredential(arg1) {
  return window['go']['main']['App']['DeleteProviderCredential'](arg1);
}

export function DeleteSkill(arg1) {
  return window['go']['main']['App']['DeleteSkill'](arg1);
}

export function ExportLocalAPIKeyEnv(arg1) {
  return window['go']['main']['App']['ExportLocalAPIKeyEnv'](arg1);
}

export function FetchProviderIcon(arg1) {
  return window['go']['main']['App']['FetchProviderIcon'](arg1);
}

export function FetchProviderModels(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FetchProviderModels'](arg1, arg2, arg3, arg4);
}

export function GatewayHost() {
  return window['go']['main']['App']['GatewayHost']();
}

export function GetBootstrap() {
  return window['go']['main']['App']['GetBootstrap']();
}

export function GetRequestLog(arg1) {
  return window['go']['main']['App']['GetRequestLog'](arg1);
}

export function GetSkill(arg1) {
  return window['go']['main']['App']['GetSkill'](arg1);
}

export function GetUsageBreakdown() {
  return window['go']['main']['App']['GetUsageBreakdown']();
}

export function ListDevModels() {
  return window['go']['main']['App']['ListDevModels']();
}

export function ListDevProviders() {
  return window['go']['main']['App']['ListDevProviders']();
}

export function ListPlugins() {
  return window['go']['main']['App']['ListPlugins']();
}

export function ListProviderCredentials(arg1) {
  return window['go']['main']['App']['ListProviderCredentials'](arg1);
}

export function ListRequestLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListRequestLogs'](arg1, arg2, arg3);
}

export function ListSkillLinks(arg1) {
  return window['go']['main']['App']['ListSkillLinks'](arg1);
}

export function ListSkills() {
  return window['go']['main']['App']['ListSkills']();
}

export function ListToolTemplates() {
  return window['go']['main']['App']['ListToolTemplates']();
}

export function LocalAPIKeyEnvStatus(arg1) {
  return window['go']['main']['App']['LocalAPIKeyEnvStatus'](arg1);
}

export function PlaygroundChat(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PlaygroundChat'](arg1, arg2, arg3, arg4);
}

export function RefreshDevModels() {
  return window['go']['main']['App']['RefreshDevModels']();
}

export function RefreshDevProviders() {
  return window['go']['main']['App']['RefreshDevProviders']();
}

export function RenderToolTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenderToolTemplate'](arg1, arg2, arg3);
}

export function ResetProviderCredentialStatus(arg1) {
  return window['go']['main']['App']['ResetProviderCredentialStatus'](arg1);
}

export function ResolveModel(arg1) {
  return window['go']['main']['App']['ResolveModel'](arg1);
}

export function SaveAgentPreset(arg1) {
  return window['go']['main']['App']['SaveAgentPreset'](arg1);
}

export function SaveLocalAPIKey(arg1) {
  return window['go']['main']['App']['SaveLocalAPIKey'](arg1);
}

export function SaveModelMapping(arg1) {
  return window['go']['main']['App']['SaveModelMapping'](arg1);
}

export function SaveProvider(arg1) {
  return window['go']['main']['App']['SaveProvider'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SaveSkillBody(arg1, arg2) {
  return window['go']['main']['App']['SaveSkillBody'](arg1, arg2);
}

export function SetChainMode(arg1, arg2) {
  return window['go']['main']['App']['SetChainMode'](arg1, arg2);
}

export function SetPluginConfig(arg1, arg2) {
  return window['go']['main']['App']['SetPluginConfig'](arg1, arg2);
}

export function SetProviderAPIKey(arg1, arg2) {
  return window['go']['main']['App']['SetProviderAPIKey'](arg1, arg2);
}

export function SetProviderCredentialMode(arg1, arg2) {
  return window['go']['main']['App']['SetProviderCredentialMode'](arg1, arg2);
}

export function SetProxyRunning(arg1) {
  return window['go']['main']['App']['SetProxyRunning'](arg1);
}

export function SetSkillLink(arg1, arg2, arg3) {
  return window['go']['main']['App']['SetSkillLink'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function ToggleLocalAPIKey(arg1, arg2) {
  return window['go']['main']['App']['ToggleLocalAPIKey'](arg1, arg2);
}

export function TogglePlugin(arg1, arg2) {
  return window['go']['main']['App']['TogglePlugin'](arg1, arg2);
}

export function ToggleProvider(arg1, arg2) {
  return window['go']['main']['App']['ToggleProvider'](arg1, arg2);
}

export function ToggleProviderCredential(arg1, arg2) {
  return window['go']['main']['App']['ToggleProviderCredential'](arg1, arg2);
}

export function ToggleSkill(arg1, arg2) {
  return window['go']['main']['App']['ToggleSkill'](arg1, arg2);
}

export function UpdateProviderCredential(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProviderCredential'](arg1, arg2, arg3);
}

export function WriteToolTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteToolTemplate'](arg1, arg2, arg3);
}
