// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {credential} from '../models';
import {envcfg} from '../models';
import {provider} from '../models';
import {main} from '../models';
import {usage} from '../models';
import {skills} from '../models';
import {templates} from '../models';
import {proxy} from '../models';
import {config} from '../models';
import {agent} from '../models';
import {apikey} from '../models';
import {settings} from '../models';
import {context} from '../models';

export function AddProviderCredential(arg1:string,arg2:string,arg3:string):Promise<credential.Credential>;

export function CancelPlayground():Promise<void>;

export function DeleteLocalAPIKey(arg1:string):Promise<void>;

export function DeleteProvider(arg1:string):Promise<void>;

export function DeleteProviderCredential(arg1:string):Promise<void>;

export function DeleteSkill(arg1:string):Promise<void>;

export function ExportLocalAPIKeyEnv(arg1:string):Promise<envcfg.Status>;

export function FetchProviderIcon(arg1:string):Promise<string>;

export function FetchProviderModels(arg1:string,arg2:string,arg3:string,arg4:string):Promise<Array<provider.AvailableModel>>;

export function GatewayHost():Promise<string>;

export function GetBootstrap():Promise<main.Bootstrap>;

export function GetRequestLog(arg1:number):Promise<usage.RequestLog>;

export function GetSkill(arg1:string):Promise<skills.Detail>;

export function GetUsageBreakdown():Promise<usage.Breakdown>;

export function ListProviderCredentials(arg1:string):Promise<Array<credential.Credential>>;

export function ListRequestLogs(arg1:number,arg2:number,arg3:usage.RequestLogFilter):Promise<usage.RequestLogPage>;

export function ListSkillLinks(arg1:string):Promise<main.ToolSkillLinks>;

export function ListSkills():Promise<main.SkillSummary>;

export function ListToolTemplates():Promise<Array<templates.Preview>>;

export function LocalAPIKeyEnvStatus(arg1:string):Promise<envcfg.Status>;

export function PlaygroundChat(arg1:string,arg2:string,arg3:Array<proxy.Message>,arg4:string):Promise<main.PlaygroundResult>;

export function RenderToolTemplate(arg1:templates.ToolID,arg2:Record<string, string>,arg3:Array<string>):Promise<templates.Preview>;

export function ResetProviderCredentialStatus(arg1:string):Promise<void>;

export function ResolveModel(arg1:string):Promise<config.ModelMapping>;

export function SaveAgentPreset(arg1:agent.Preset):Promise<agent.Preset>;

export function SaveLocalAPIKey(arg1:apikey.Key):Promise<apikey.Key>;

export function SaveModelMapping(arg1:config.ModelMapping):Promise<config.ModelMapping>;

export function SaveProvider(arg1:provider.Provider):Promise<provider.Provider>;

export function SaveSettings(arg1:settings.Settings):Promise<settings.Settings>;

export function SaveSkillBody(arg1:string,arg2:string):Promise<void>;

export function SetProviderAPIKey(arg1:string,arg2:string):Promise<void>;

export function SetProviderCredentialMode(arg1:string,arg2:string):Promise<void>;

export function SetProxyRunning(arg1:boolean):Promise<void>;

export function SetSkillLink(arg1:string,arg2:string,arg3:boolean):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function ToggleLocalAPIKey(arg1:string,arg2:boolean):Promise<void>;

export function ToggleProvider(arg1:string,arg2:boolean):Promise<void>;

export function ToggleProviderCredential(arg1:string,arg2:boolean):Promise<void>;

export function ToggleSkill(arg1:string,arg2:boolean):Promise<skills.Skill>;

export function UpdateProviderCredential(arg1:string,arg2:string,arg3:number):Promise<credential.Credential>;

export function WriteToolTemplate(arg1:templates.ToolID,arg2:Record<string, string>,arg3:Array<string>):Promise<string>;
