// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteLocalAPIKey(arg1) {
  return window['go']['main']['App']['DeleteLocalAPIKey'](arg1);
}

export function DeleteProvider(arg1) {
  return window['go']['main']['App']['DeleteProvider'](arg1);
}

export function ExportLocalAPIKeyEnv(arg1) {
  return window['go']['main']['App']['ExportLocalAPIKeyEnv'](arg1);
}

export function FetchProviderIcon(arg1) {
  return window['go']['main']['App']['FetchProviderIcon'](arg1);
}

export function FetchProviderModels(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FetchProviderModels'](arg1, arg2, arg3, arg4);
}

export function GatewayHost() {
  return window['go']['main']['App']['GatewayHost']();
}

export function GetBootstrap() {
  return window['go']['main']['App']['GetBootstrap']();
}

export function GetRequestLog(arg1) {
  return window['go']['main']['App']['GetRequestLog'](arg1);
}

export function GetUsageBreakdown() {
  return window['go']['main']['App']['GetUsageBreakdown']();
}

export function ListRequestLogs(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListRequestLogs'](arg1, arg2, arg3);
}

export function ListToolTemplates() {
  return window['go']['main']['App']['ListToolTemplates']();
}

export function LocalAPIKeyEnvStatus(arg1) {
  return window['go']['main']['App']['LocalAPIKeyEnvStatus'](arg1);
}

export function RenderToolTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['RenderToolTemplate'](arg1, arg2, arg3);
}

export function ResolveModel(arg1) {
  return window['go']['main']['App']['ResolveModel'](arg1);
}

export function SaveAgentPreset(arg1) {
  return window['go']['main']['App']['SaveAgentPreset'](arg1);
}

export function SaveLocalAPIKey(arg1) {
  return window['go']['main']['App']['SaveLocalAPIKey'](arg1);
}

export function SaveModelMapping(arg1) {
  return window['go']['main']['App']['SaveModelMapping'](arg1);
}

export function SaveProvider(arg1) {
  return window['go']['main']['App']['SaveProvider'](arg1);
}

export function SetProviderAPIKey(arg1, arg2) {
  return window['go']['main']['App']['SetProviderAPIKey'](arg1, arg2);
}

export function SetProxyRunning(arg1) {
  return window['go']['main']['App']['SetProxyRunning'](arg1);
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function ToggleLocalAPIKey(arg1, arg2) {
  return window['go']['main']['App']['ToggleLocalAPIKey'](arg1, arg2);
}

export function ToggleProvider(arg1, arg2) {
  return window['go']['main']['App']['ToggleProvider'](arg1, arg2);
}

export function WriteToolTemplate(arg1, arg2, arg3) {
  return window['go']['main']['App']['WriteToolTemplate'](arg1, arg2, arg3);
}
